In [1]:
import pandas as pd

In [ ]:
df = pd.DataFrame ({
    "cliente": [1,2,3,4,5],
    "nome": ["teo","jose","maria","alfredo","romeu"]
})

df_02 = pd.DataFrame ({
    "cliente": [6,7,8],
    "nome": ["afonso","shirley","pedro"],
    "idade": [32,29,31]
})

df_03 = pd.DataFrame ({
    "idade": [32,34,19,54,33]
})
dfs = [df,df_02]

In [ ]:
#concatena listas um em cima do outro
pd.concat(dfs, ignore_index=True)

   cliente     nome  idade
0        1      teo    NaN
1        2     jose    NaN
2        3    maria    NaN
3        4  alfredo    NaN
4        5    romeu    NaN
5        6   afonso   32.0
6        7  shirley   29.0
7        8    pedro   31.0

In [10]:
#concatena um ao lado do outro
pd.concat([df,df_03], axis=1)

   cliente     nome  idade
0        1      teo     32
1        2     jose     34
2        3    maria     19
3        4  alfredo     54
4        5    romeu     33

In [ ]:
#ordenou
df_03 = df_03.sort_values(by="idade")
df_03

   idade
2     19
0     32
4     33
1     34
3     54

In [ ]:
#está ordenando por index e não por valor de idade
pd.concat([df, df_03], axis=1)

   cliente     nome  idade
0        1      teo     32
1        2     jose     34
2        3    maria     19
3        4  alfredo     54
4        5    romeu     33

In [15]:
df_03 = df_03.sort_values(by="idade").reset_index(drop=True)
df_03

   idade
0     19
1     32
2     33
3     34
4     54

In [14]:
pd.concat([df, df_03], axis=1)

   cliente     nome  idade
0        1      teo     19
1        2     jose     32
2        3    maria     33
3        4  alfredo     34
4        5    romeu     54