In [4]:
import pandas as pd
import sqlalchemy
from sklearn import cluster
with open ("etl.sql") as open_file:
    query = open_file.read()

query

'SELECT seller_id,\n    SUM(t1.price) AS totalRevenue,\n    COUNT(DISTINCT t1.order_id) AS qtSalles\n\nFROM tb_order_items AS t1\nGROUP BY seller_id'

In [3]:
engine = sqlalchemy.create_engine("sqlite:///data/olist.db")

df = pd.read_sql_query(query, con=engine)
df

                             seller_id  totalRevenue  qtSalles
0     0015a82c2db000af6aaaf3ae2ecb0532       2685.00         3
1     001cca7ae9ae17fb1caed9dfb1094831      25080.03       200
2     001e6ad469a905060d959994f1b41e4f        250.00         1
3     002100f778ceb8431b7a1020ff7ab48f       1234.50        51
4     003554e2dce176b5555353e4f3555ac8        120.00         1
...                                ...           ...       ...
3090  ffcfefa19b08742c5d315f2791395ee5         69.90         1
3091  ffdd9f82b9a447f6f8d4b91554cc7dd3       2101.20        18
3092  ffeee66ac5d5a62fe688b9d26f83f534       1839.86        14
3093  fffd5413c0700ac820c7069d66d98c89       9062.30        60
3094  ffff564a4f9085cd26170f4732393726       1426.30        20

[3095 rows x 3 columns]

In [6]:
kmean = cluster.KMeans(n_clusters=4)
kmean.fit(df[["totalRevenue",	"qtSalles"]])

df["cluster"] = kmean.labels_
df

                             seller_id  totalRevenue  qtSalles  cluster
0     0015a82c2db000af6aaaf3ae2ecb0532       2685.00         3        0
1     001cca7ae9ae17fb1caed9dfb1094831      25080.03       200        3
2     001e6ad469a905060d959994f1b41e4f        250.00         1        0
3     002100f778ceb8431b7a1020ff7ab48f       1234.50        51        0
4     003554e2dce176b5555353e4f3555ac8        120.00         1        0
...                                ...           ...       ...      ...
3090  ffcfefa19b08742c5d315f2791395ee5         69.90         1        0
3091  ffdd9f82b9a447f6f8d4b91554cc7dd3       2101.20        18        0
3092  ffeee66ac5d5a62fe688b9d26f83f534       1839.86        14        0
3093  fffd5413c0700ac820c7069d66d98c89       9062.30        60        3
3094  ffff564a4f9085cd26170f4732393726       1426.30        20        0

[3095 rows x 4 columns]

In [9]:
df.to_sql("sellers_cluster", con=engine, index=False,if_exists="replace")

3095