In [3]:
import pandas as pd

df_transacoes = pd.read_csv ("data/transacoes.csv", sep= ";")
df_transacoes.head()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [5]:
df_clientes = pd.read_csv ("data/clientes.csv", sep=";")
df_clientes.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [ ]:
df_transacoes.merge(right=df_clientes, 
                    how='left', 
                    left_on=["IdCliente"], 
                    right_on=["idCliente"],
                    suffixes=["Transacao","Cliente"]) #para colunas repetidas do mesmo dataset, usa sufixo

,IdTransacao,IdCliente,DtCriacaoTransacao,QtdePontos,DescSistemaOrigem,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacaoCliente,DtAtualizacao
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch,24782f0b-4683-4f35-976a-ea21d6714ba6,0,1,0,0,0,1957,2025-03-07 13:13:37.524,2026-03-06 13:48:04.396
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch,252a0923-3f79-45bb-b664-3040235c6c58,0,1,0,0,0,1966,2024-11-29 11:36:40.662,2025-04-28 11:33:29.687
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch,30f45a6d-ada5-4a17-8338-710e414eb6c6,0,1,0,0,0,2489,2025-03-07 12:27:12.379,2026-03-05 12:23:10.917
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch,65662aff-44d6-4f06-b9d9-07445c6e5943,1,1,1,0,0,1699,2025-03-07 13:13:25.571,2026-03-05 12:42:08.314
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,1,1,0,0,0,668,2025-03-07 12:39:26.765,2026-03-05 12:40:47.813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302231,ffff45c7-83dc-4fa9-82b5-b41352093596,6313ceac-7806-4d34-aedd-476eed7c853a,2025-01-03 12:59:27.229,1,twitch,6313ceac-7806-4d34-aedd-476eed7c853a,1,1,1,0,0,9350,2025-03-07 12:41:02.305,2026-03-06 11:32:28.038
302232,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-24 12:22:26.313,1,twitch,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,1,1,0,0,0,668,2025-03-07 12:39:26.765,2026-03-05 12:40:47.813
302233,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-08-16 13:09:42.576,1,twitch,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,0,1,0,0,0,1365,2025-03-07 13:13:26.026,2026-03-06 14:56:20.216
302234,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,2024-02-06 11:51:24.788,1,twitch,2d3d2dce-d353-4961-ad39-46723efe2100,1,1,1,0,0,2092,2025-03-07 12:40:51.664,2026-02-26 12:30:41.838
302235,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-08-21 14:13:31.788,1,twitch,65662aff-44d6-4f06-b9d9-07445c6e5943,1,1,1,0,0,1699,2025-03-07 13:13:25.571,2026-03-05 12:42:08.314

In [42]:
df_transacao_produto = pd.read_csv("data/transacao_produto.csv", sep=";")
df_transacao_produto

,idTransacaoProduto,IdTransacao,IdProduto,QtdeProduto,vlProduto
0,000026d0-4d4e-4fed-934a-9e5b26d9e379,d59d9859-8fb9-41cc-a296-be38c4dce8e4,5,1,1
1,00002f54-dd03-4b3f-ade0-22c3e61df8c2,519241fd-2676-49b2-8e74-0acc09a08f69,5,1,1
2,00006a7d-c83a-44ca-aad9-e8a2a2f1b64d,73993c42-d18f-4f51-82c4-25e13c29962c,11,1,50
3,0000991a-e6ae-4b9f-8747-c6cfe77890dd,db341350-16e4-49ea-96d4-c3e991e7c8c0,5,1,1
4,0000d145-c8b5-48fb-9ea3-d91eba3af306,7ee57139-6183-4cd6-8960-b5b14884aefb,5,1,1
...,...,...,...,...,...
302579,fffd9569-31e6-4515-8494-4edeabc0cfc2,6baf63b1-d05a-419d-a84f-abdf6906fef8,11,1,50
302580,fffe7e68-c450-4025-9469-e5cbe7699b49,90f7149b-5794-4d49-9239-c3bddb5b0980,5,1,1
302581,fffead0f-105b-4517-ac6f-b60ffd66f0dd,a5240b8c-c015-4d4c-8e34-2e81973ad084,5,1,1
302582,ffff210a-2594-42fa-8d85-c97483817542,4d7c74c0-5ca0-4786-823b-b393d505c2e6,5,1,1
302583,ffff2827-d194-42ac-8a62-90b1a745eddf,410a177d-1234-4a0f-b1e2-456db06a99ba,5,1,1

In [41]:
df_produto = pd.read_csv("data/produtos.csv", sep=";")
df_produto.head(14)

,IdProduto,DescNomeProduto,DescDescricaoProduto,DescCategoriaProduto
0,001 - Espada Longa,Espada Longa,Uma espada longa de aço.,espada
1,002 - Espada Curta,Espada Curta,Espada leve e rápida.,espada
2,003 - Armadura de Couro,Armadura de Couro,Armadura leve feita de couro.,armadura
3,004 - Armadura de Placas,Armadura de Placas,Armadura pesada de placas metálicas.,armadura
4,005 - Botas de Agilidade,Botas de Agilidade,Botas que aumentam a destreza.,botas
5,006 - Botas de Força,Botas de Força,Botas reforçadas para guerreiros.,botas
6,007 - Cajado de Fogo,Cajado de Fogo,Cajado mágico que lança fogo.,cajado
7,008 - Cajado de Gelo,Cajado de Gelo,Cajado mágico que lança gelo.,cajado
8,009 - Chapéu do Mago,Chapéu do Mago,Chapéu pontudo que aumenta inteligência.,chapeu
9,010 - Chapéu do Sábio,Chapéu do Sábio,Chapéu que aumenta sabedoria.,chapeu
10,011 - Espada Bastarda,Espada Bastarda,Espada de duas mãos.,espada
11,012 - Armadura de Escamas,Armadura de Escamas,Armadura feita de escamas de dragão.,armadura
12,013 - Botas Silenciosas,Botas Silenciosas,Botas que aumentam furtividade.,botas
13,014 - Cajado da Vida,Cajado da Vida,Cajado que aumenta sabedoria.,cajado

In [40]:
cliente_transacao_produto = df_transacoes.merge(df_transacao_produto, on="IdTransacao",how="left")

In [ ]:
#filtrando
cliente_transacao_produto[["IdTransacao","IdCliente","IdProduto"]]

,IdTransacao,IdCliente,IdProduto
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,5
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,5
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,5
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,5
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5
...,...,...,...
302579,ffff45c7-83dc-4fa9-82b5-b41352093596,6313ceac-7806-4d34-aedd-476eed7c853a,5
302580,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5
302581,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,5
302582,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,5
302583,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,5

In [53]:
df_full = cliente_transacao_produto.merge(df_produto, on=["IdProduto"], how="left")
df_full.head()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,idTransacaoProduto,IdProduto,QtdeProduto,vlProduto,DescNomeProduto,DescDescricaoProduto,DescCategoriaProduto
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch,dbbfdc7c-84b2-4536-b1a8-abb7a475875c,5,1,1,ChatMessage,NaN,chat
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch,9d90f1a5-2442-429f-a913-37f2734979ef,5,1,1,ChatMessage,NaN,chat
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch,ff90b953-f715-4b97-b511-c4f78f725f33,5,1,1,ChatMessage,NaN,chat
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch,a31fc987-77e0-4510-b9c8-769f4d0714a4,5,1,1,ChatMessage,NaN,chat
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch,85293b0c-399d-4590-a2a8-9943825d62e9,5,1,1,ChatMessage,NaN,chat

In [ ]:
df_full = df_full[df_full["DescNomeProduto"]=="Presença Streak"]
df_full.groupby(by=["IdCliente"])["IdTransacao"].count().sort_values(ascending=False).head(1)

IdCliente
6313ceac-7806-4d34-aedd-476eed7c853a    373
Name: IdTransacao, dtype: int64