In [4]:
import pandas as pd

In [5]:

clientes = pd.read_csv ("data/clientes.csv", sep=";")
clientes

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5066,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
5067,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
5068,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5069,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5070,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561

In [8]:
clientes=clientes.dropna()
clientes

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5066,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
5067,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
5068,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5069,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5070,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561

In [9]:
clientes.isna().sum()

idCliente        0
flEmail          0
flTwitch         0
flYouTube        0
flBlueSky        0
flInstagram      0
qtdePontos       0
DtCriacao        0
DtAtualizacao    0
dtype: int64

In [10]:
df = pd.DataFrame ({
    "nome": ["teo", None, "maria", "marcos"],
    "idade": [None, None, 45,50],
    "salario": [3455,3345,None, 2224]
})

df.dropna(how="all", subset=["idade", "salario"])

     nome  idade  salario
0     teo    NaN   3455.0
1    None    NaN   3345.0
2   maria   45.0      NaN
3  marcos   50.0   2224.0

In [ ]:
df["idade"].fillna(0) #preenche os valores nulos com 0

0     0.0
1     0.0
2    45.0
3    50.0
Name: idade, dtype: float64

In [12]:
medias = df[["idade","salario"]].mean()
df.fillna(medias)

     nome  idade  salario
0     teo   47.5   3455.0
1    None   47.5   3345.0
2   maria   45.0   3008.0
3  marcos   50.0   2224.0

In [14]:
names_df = pd.DataFrame ({
    "nome": ["teo", "lara", "lara", "marcos", "ana", "teo","bia"],
    "sobrenome": ["calvo", "silva", "silva", "ataide","oliveira","calvo", "oliveira"],
    "salario": [2323, 4645, 6342, 23523,6464, 1356, 43652]
})

names_df

     nome sobrenome  salario
0     teo     calvo     2323
1    lara     silva     4645
2    lara     silva     6342
3  marcos    ataide    23523
4     ana  oliveira     6464
5     teo     calvo     1356
6     bia  oliveira    43652

In [15]:
names_df.drop_duplicates()

     nome sobrenome  salario
0     teo     calvo     2323
1    lara     silva     4645
2    lara     silva     6342
3  marcos    ataide    23523
4     ana  oliveira     6464
5     teo     calvo     1356
6     bia  oliveira    43652

In [22]:
names_df.sort_values("salario", ascending=False)

     nome sobrenome  salario
6     bia  oliveira    43652
3  marcos    ataide    23523
4     ana  oliveira     6464
2    lara     silva     6342
1    lara     silva     4645
0     teo     calvo     2323
5     teo     calvo     1356

In [24]:
names_df = (names_df.drop_duplicates(keep='last', subset=["nome", "sobrenome"]))
names_df

     nome sobrenome  salario
6     bia  oliveira    43652
3  marcos    ataide    23523
4     ana  oliveira     6464
1    lara     silva     4645
5     teo     calvo     1356